# compose.dev.yaml (DEVELOPMENT OVERRIDE)
version: "3.9"

services:
  web:
    build:
      # Override the Dockerfile to use the development version
      dockerfile: Dockerfile.dev
    # Override the command to use the dev server
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      # Expose the development port
      - "8000:8000"
    volumes:
      # Add the live-reloading volume
      - ./src:/app
    depends_on:
      db:
        # Add a healthcheck condition for smoother startup
        condition: service_healthy
