# Generated by Django 5.2.6 on 2025-09-28 03:59

from django.db import migrations


def seed_initial_data(apps, schema_editor):
    """Seeds the database with an expanded set of initial categories and products."""
    Category = apps.get_model("shop", "Category")
    Product = apps.get_model("shop", "Product")

    # --- Create Categories (WITH DESCRIPTIONS) ---
    electronics, _ = Category.objects.get_or_create(
        name="Electronics",
        defaults={
            "slug": "electronics",
            "description": "Gadgets, devices, and all things electronic.",
        },
    )
    books, _ = Category.objects.get_or_create(
        name="Books",
        defaults={
            "slug": "books",
            "description": "Fiction, non-fiction, and everything in between.",
        },
    )
    clothing, _ = Category.objects.get_or_create(
        name="Clothing",
        defaults={
            "slug": "clothing",
            "description": "Apparel for all styles and seasons.",
        },
    )
    home_goods, _ = Category.objects.get_or_create(
        name="Home Goods",
        defaults={
            "slug": "home-goods",
            "description": "Items to furnish and improve your home.",
        },
    )
    sports, _ = Category.objects.get_or_create(
        name="Sports & Outdoors",
        defaults={
            "slug": "sports-outdoors",
            "description": "Equipment for an active lifestyle.",
        },
    )
    toys, _ = Category.objects.get_or_create(
        name="Toys & Games",
        defaults={"slug": "toys-games", "description": "Fun and games for all ages."},
    )

    # --- Create Products ---
    products_to_create = [
        # Electronics
        {
            "name": "Wireless Noise-Cancelling Headphones",
            "category": electronics,
            "description": "High-fidelity audio with adaptive noise cancellation.",
            "price": "249.99",
            "stock": 50,
        },
        {
            "name": "4K Ultra HD Smart TV",
            "category": electronics,
            "description": "A 55-inch smart TV with stunning 4K resolution and HDR.",
            "price": "499.99",
            "stock": 25,
        },
        {
            "name": "Portable Bluetooth Speaker",
            "category": electronics,
            "description": "Waterproof and dustproof speaker with 12-hour battery life.",
            "price": "79.99",
            "stock": 100,
        },
        {
            "name": "E-Reader Tablet",
            "category": electronics,
            "description": "A 6-inch glare-free display that reads like real paper, even in direct sunlight.",
            "price": "129.99",
            "stock": 80,
        },
        # Books
        {
            "name": "The Three-Body Problem",
            "category": books,
            "description": "A science fiction masterpiece by Cixin Liu.",
            "price": "15.99",
            "stock": 150,
        },
        {
            "name": "Dune",
            "category": books,
            "description": "Frank Herbert's epic science fiction novel set on the desert planet Arrakis.",
            "price": "18.00",
            "stock": 200,
        },
        {
            "name": "Sapiens: A Brief History of Humankind",
            "category": books,
            "description": "Yuval Noah Harari's exploration of human history.",
            "price": "22.50",
            "stock": 120,
        },
        # Clothing
        {
            "name": "Organic Cotton T-Shirt",
            "category": clothing,
            "description": "A soft, breathable, and sustainably sourced t-shirt.",
            "price": "25.00",
            "stock": 300,
        },
        {
            "name": "All-Weather Hiking Boots",
            "category": clothing,
            "description": "Durable and waterproof boots for any terrain.",
            "price": "140.00",
            "stock": 60,
        },
        # Home Goods
        {
            "name": "Smart LED Light Bulb",
            "category": home_goods,
            "description": "A multi-color smart bulb compatible with voice assistants.",
            "price": "19.99",
            "stock": 250,
        },
        {
            "name": "Espresso Machine",
            "category": home_goods,
            "description": "A semi-automatic espresso machine with a built-in grinder.",
            "price": "599.00",
            "stock": 15,
        },
        # Sports & Outdoors
        {
            "name": "Yoga Mat",
            "category": sports,
            "description": "A non-slip, eco-friendly yoga mat for all types of practice.",
            "price": "35.00",
            "stock": 180,
        },
        {
            "name": "2-Person Camping Tent",
            "category": sports,
            "description": "A lightweight, waterproof tent perfect for backpacking.",
            "price": "120.00",
            "stock": 40,
        },
        # Toys & Games
        {
            "name": "Settlers of Catan Board Game",
            "category": toys,
            "description": "The classic strategy board game of trade, build, and settle.",
            "price": "49.00",
            "stock": 90,
        },
        {
            "name": "LEGO Space Shuttle Discovery",
            "category": toys,
            "description": "A detailed 2,354-piece model of the iconic NASA space shuttle.",
            "price": "199.99",
            "stock": 20,
        },
    ]

    for product_data in products_to_create:
        Product.objects.get_or_create(
            name=product_data["name"],
            category=product_data["category"],
            defaults={
                "description": product_data["description"],
                "price": product_data["price"],
                "stock": product_data["stock"],
            },
        )


class Migration(migrations.Migration):
    dependencies = [
        (
            "shop",
            "0001_initial",
        ),  # This depends on your first migration for the shop app
    ]

    operations = [
        migrations.RunPython(seed_initial_data),
    ]
