# Generated by Django 5.2.6 on 2025-09-28 03:33

from django.db import migrations


from django.db import migrations


def seed_initial_data(apps, schema_editor):
    """Seeds the database with initial categories and products."""
    # We get the model from the versioned app registry;
    # this is important for data migrations.
    Category = apps.get_model("shop", "Category")
    Product = apps.get_model("shop", "Product")

    # --- Create Categories ---
    # get_or_create prevents creating duplicates if the migration is run again.
    electronics, _ = Category.objects.get_or_create(
        name="Electronics", defaults={"slug": "electronics"}
    )
    books, _ = Category.objects.get_or_create(name="Books", defaults={"slug": "books"})
    clothing, _ = Category.objects.get_or_create(
        name="Clothing", defaults={"slug": "clothing"}
    )
    home_goods, _ = Category.objects.get_or_create(
        name="Home Goods", defaults={"slug": "home-goods"}
    )

    # --- Create Products ---
    Product.objects.get_or_create(
        name="Wireless Noise-Cancelling Headphones",
        category=electronics,
        defaults={
            "description": "High-fidelity audio with adaptive noise cancellation.",
            "price": "249.99",
        },
    )
    Product.objects.get_or_create(
        name="The Three-Body Problem",
        category=books,
        defaults={
            "description": "A science fiction masterpiece by Cixin Liu.",
            "price": "15.99",
        },
    )
    Product.objects.get_or_create(
        name="Organic Cotton T-Shirt",
        category=clothing,
        defaults={
            "description": "A soft, breathable, and sustainably sourced t-shirt.",
            "price": "25.00",
        },
    )
    Product.objects.get_or_create(
        name="Smart LED Light Bulb",
        category=home_goods,
        defaults={
            "description": "A multi-color smart bulb compatible with voice assistants.",
            "price": "19.99",
        },
    )
    Product.objects.get_or_create(
        name="4K Ultra HD Smart TV",
        category=electronics,
        defaults={
            "description": "A 55-inch smart TV with stunning 4K resolution and HDR.",
            "price": "499.99",
        },
    )


class Migration(migrations.Migration):
    dependencies = [
        (
            "shop",
            "0001_initial",
        ),  # This depends on your first migration for the shop app
    ]

    operations = [
        migrations.RunPython(seed_initial_data),
    ]
