# Generated by Django 5.2.6 on 2025-09-28 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_created_at_product_updated_at_and_more'),
        ('shop', '0004_seed_initial_data'),
    ]

    operations = [
    ]
