# Generated by Django 5.2.6 on 2025-09-28 03:41

from django.db import migrations
import os


def create_superuser(apps, schema_editor):
    """
    Creates a superuser from environment variables.
    This function is idempotent and safe to run multiple times.
    """
    # Get the CustomUser model from the historical app registry
    User = apps.get_model("users", "CustomUser")

    USERNAME = os.environ.get("ADMIN_USERNAME")
    EMAIL = os.environ.get("ADMIN_EMAIL")
    PASSWORD = os.environ.get("ADMIN_PASSWORD")

    # Only proceed if all variables are set and the user does not already exist
    if (
        all([USERNAME, EMAIL, PASSWORD])
        and not User.objects.filter(username=USERNAME).exists()
    ):
        print(f"\nCreating superuser: {USERNAME}")

        # We must use create_superuser to ensure is_staff and is_superuser are set
        User.objects.create_superuser(username=USERNAME, email=EMAIL, password=PASSWORD)
    else:
        print(
            "\nSuperuser already exists or environment variables are not set. Skipping."
        )


class Migration(migrations.Migration):
    dependencies = [
        (
            "users",
            "0001_initial",
        ),  # This depends on your first migration for the users app
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
