# Generated by Django 5.2.6 on 2025-09-28 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers'),
        ('users', '0003_create_superuser'),
    ]

    operations = [
    ]
